/*
 * Copyright (c) 2005, 2006 IBM Corporation and others.
 * All rights reserved.   This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   IBM - initial API and implementation
 *
 * $Id: UMLItemProviderAdapterFactory.java,v 1.11 2006/01/04 17:47:49 khussey Exp $
 */
package org.eclipse.uml2.uml.edit.providers;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.Disposable;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ReflectiveItemProvider;

import org.eclipse.uml2.common.edit.provider.IItemQualifiedTextProvider;
import org.eclipse.uml2.uml.Extension;
import org.eclipse.uml2.uml.util.UMLAdapterFactory;
import org.eclipse.uml2.uml.util.UMLUtil;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UMLItemProviderAdapterFactory
		extends UMLAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the item providers created, so that they can be {@link #dispose disposed}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Disposable disposable = new Disposable();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	protected final ReflectiveItemProvider stereotypeApplicationItemProvider;

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated NOT
	 */
	public UMLItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);

		supportedTypes.add(IItemQualifiedTextProvider.class);

		stereotypeApplicationItemProvider = new ReflectiveItemProvider(this) {

			public List getPropertyDescriptors(Object object) {
				itemPropertyDescriptors = new ArrayList();

				for (Iterator eAllStructuralFeatures = ((EObject) object)
					.eClass().getEAllStructuralFeatures().iterator(); eAllStructuralFeatures
					.hasNext();) {

					EStructuralFeature eStructuralFeature = (EStructuralFeature) eAllStructuralFeatures
						.next();
					boolean isBaseReference = eStructuralFeature.getName()
						.startsWith(Extension.METACLASS_ROLE_PREFIX);
					String[] filterFlags = isBaseReference
						|| (eStructuralFeature instanceof EReference && ((EReference) eStructuralFeature)
							.isContainment())
						? new String[]{"org.eclipse.ui.views.properties.expert"} //$NON-NLS-1$
						: null;

					itemPropertyDescriptors.add(new UMLItemPropertyDescriptor(
						((ComposeableAdapterFactory) adapterFactory)
							.getRootAdapterFactory(), null,
						getFeatureText(eStructuralFeature),
						getResourceLocator().getString(
							"_UI_Property_description", //$NON-NLS-1$
							new Object[]{getFeatureText(eStructuralFeature),
								eStructuralFeature.getEType().getName()}),
						eStructuralFeature, !isBaseReference
							&& eStructuralFeature.isChangeable(),
						ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
						getTypeText(object), filterFlags));
				}

				return itemPropertyDescriptors;
			}

			public String getText(Object object) {

				if (object instanceof EObject
					&& UMLUtil.getStereotype((EObject) object) != null) {

					return super.getText(object)
						+ " -> " //$NON-NLS-1$
						+ UMLUtil.getQualifiedText(UMLUtil
							.getBaseElement((EObject) object));
				}

				return super.getText(object);
			}
		};
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Comment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCommentAdapter() {
		return new CommentItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Dependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDependencyAdapter() {
		return new DependencyItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TemplateParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTemplateParameterAdapter() {
		return new TemplateParameterItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TemplateSignature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTemplateSignatureAdapter() {
		return new TemplateSignatureItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TemplateBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTemplateBindingAdapter() {
		return new TemplateBindingItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TemplateParameterSubstitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTemplateParameterSubstitutionAdapter() {
		return new TemplateParameterSubstitutionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ElementImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createElementImportAdapter() {
		return new ElementImportItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.PackageImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPackageImportAdapter() {
		return new PackageImportItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Package}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPackageAdapter() {
		return new PackageItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.PackageMerge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPackageMergeAdapter() {
		return new PackageMergeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ProfileApplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProfileApplicationAdapter() {
		return new ProfileApplicationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Profile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProfileAdapter() {
		return new ProfileItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Stereotype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStereotypeAdapter() {
		return new StereotypeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Image}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createImageAdapter() {
		return new ImageItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Class}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClassAdapter() {
		return new ClassItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Generalization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGeneralizationAdapter() {
		return new GeneralizationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.GeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGeneralizationSetAdapter() {
		return new GeneralizationSetItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.UseCase}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUseCaseAdapter() {
		return new UseCaseItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Include}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createIncludeAdapter() {
		return new IncludeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Extend}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtendAdapter() {
		return new ExtendItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Constraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConstraintAdapter() {
		return new ConstraintItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExtensionPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtensionPointAdapter() {
		return new ExtensionPointItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Substitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSubstitutionAdapter() {
		return new SubstitutionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Realization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRealizationAdapter() {
		return new RealizationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Abstraction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAbstractionAdapter() {
		return new AbstractionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.OpaqueExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOpaqueExpressionAdapter() {
		return new OpaqueExpressionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createParameterAdapter() {
		return new ParameterItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ConnectorEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConnectorEndAdapter() {
		return new ConnectorEndItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPropertyAdapter() {
		return new PropertyItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Deployment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDeploymentAdapter() {
		return new DeploymentItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DeploymentSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDeploymentSpecificationAdapter() {
		return new DeploymentSpecificationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Artifact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createArtifactAdapter() {
		return new ArtifactItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Manifestation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createManifestationAdapter() {
		return new ManifestationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOperationAdapter() {
		return new OperationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ParameterSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createParameterSetAdapter() {
		return new ParameterSetItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDataTypeAdapter() {
		return new DataTypeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Interface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInterfaceAdapter() {
		return new InterfaceItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Reception}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReceptionAdapter() {
		return new ReceptionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Signal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSignalAdapter() {
		return new SignalItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ProtocolStateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProtocolStateMachineAdapter() {
		return new ProtocolStateMachineItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.StateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStateMachineAdapter() {
		return new StateMachineItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Region}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRegionAdapter() {
		return new RegionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Transition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTransitionAdapter() {
		return new TransitionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Trigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTriggerAdapter() {
		return new TriggerItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPortAdapter() {
		return new PortItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStateAdapter() {
		return new StateItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ConnectionPointReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConnectionPointReferenceAdapter() {
		return new ConnectionPointReferenceItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Pseudostate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPseudostateAdapter() {
		return new PseudostateItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ProtocolConformance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProtocolConformanceAdapter() {
		return new ProtocolConformanceItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.OperationTemplateParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOperationTemplateParameterAdapter() {
		return new OperationTemplateParameterItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Association}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAssociationAdapter() {
		return new AssociationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ConnectableElementTemplateParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConnectableElementTemplateParameterAdapter() {
		return new ConnectableElementTemplateParameterItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CollaborationUse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCollaborationUseAdapter() {
		return new CollaborationUseItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Collaboration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCollaborationAdapter() {
		return new CollaborationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Connector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConnectorAdapter() {
		return new ConnectorItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.RedefinableTemplateSignature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRedefinableTemplateSignatureAdapter() {
		return new RedefinableTemplateSignatureItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ClassifierTemplateParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClassifierTemplateParameterAdapter() {
		return new ClassifierTemplateParameterItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InterfaceRealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInterfaceRealizationAdapter() {
		return new InterfaceRealizationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Extension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtensionAdapter() {
		return new ExtensionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExtensionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExtensionEndAdapter() {
		return new ExtensionEndItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.StringExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStringExpressionAdapter() {
		return new StringExpressionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Expression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExpressionAdapter() {
		return new ExpressionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LiteralInteger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLiteralIntegerAdapter() {
		return new LiteralIntegerItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LiteralString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLiteralStringAdapter() {
		return new LiteralStringItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LiteralBoolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLiteralBooleanAdapter() {
		return new LiteralBooleanItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LiteralNull}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLiteralNullAdapter() {
		return new LiteralNullItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Slot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSlotAdapter() {
		return new SlotItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InstanceSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInstanceSpecificationAdapter() {
		return new InstanceSpecificationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Enumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEnumerationAdapter() {
		return new EnumerationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.EnumerationLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEnumerationLiteralAdapter() {
		return new EnumerationLiteralItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.PrimitiveType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPrimitiveTypeAdapter() {
		return new PrimitiveTypeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InstanceValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInstanceValueAdapter() {
		return new InstanceValueItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LiteralUnlimitedNatural}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLiteralUnlimitedNaturalAdapter() {
		return new LiteralUnlimitedNaturalItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.OpaqueBehavior}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOpaqueBehaviorAdapter() {
		return new OpaqueBehaviorItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.FunctionBehavior}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFunctionBehaviorAdapter() {
		return new FunctionBehaviorItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActorAdapter() {
		return new ActorItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Usage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUsageAdapter() {
		return new UsageItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Message}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMessageAdapter() {
		return new MessageItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Interaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInteractionAdapter() {
		return new InteractionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Lifeline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLifelineAdapter() {
		return new LifelineItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.PartDecomposition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPartDecompositionAdapter() {
		return new PartDecompositionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InteractionUse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInteractionUseAdapter() {
		return new InteractionUseItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Gate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGateAdapter() {
		return new GateItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActionAdapter() {
		return new ActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Activity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivityAdapter() {
		return new ActivityItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ActivityPartition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivityPartitionAdapter() {
		return new ActivityPartitionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.StructuredActivityNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStructuredActivityNodeAdapter() {
		return new StructuredActivityNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Variable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createVariableAdapter() {
		return new VariableItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InterruptibleActivityRegion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInterruptibleActivityRegionAdapter() {
		return new InterruptibleActivityRegionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExceptionHandler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExceptionHandlerAdapter() {
		return new ExceptionHandlerItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.OutputPin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOutputPinAdapter() {
		return new OutputPinItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Pin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPinAdapter() {
		return new PinItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InputPin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInputPinAdapter() {
		return new InputPinItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.GeneralOrdering}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGeneralOrderingAdapter() {
		return new GeneralOrderingItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InteractionOperand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInteractionOperandAdapter() {
		return new InteractionOperandItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InteractionConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInteractionConstraintAdapter() {
		return new InteractionConstraintItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExecutionOccurrenceSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExecutionOccurrenceSpecificationAdapter() {
		return new ExecutionOccurrenceSpecificationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExecutionEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExecutionEventAdapter() {
		return new ExecutionEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.StateInvariant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStateInvariantAdapter() {
		return new StateInvariantItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ActionExecutionSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActionExecutionSpecificationAdapter() {
		return new ActionExecutionSpecificationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.BehaviorExecutionSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createBehaviorExecutionSpecificationAdapter() {
		return new BehaviorExecutionSpecificationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CreationEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCreationEventAdapter() {
		return new CreationEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DestructionEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDestructionEventAdapter() {
		return new DestructionEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.SendOperationEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSendOperationEventAdapter() {
		return new SendOperationEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.SendSignalEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSendSignalEventAdapter() {
		return new SendSignalEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.MessageOccurrenceSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMessageOccurrenceSpecificationAdapter() {
		return new MessageOccurrenceSpecificationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReceiveOperationEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReceiveOperationEventAdapter() {
		return new ReceiveOperationEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReceiveSignalEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReceiveSignalEventAdapter() {
		return new ReceiveSignalEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CombinedFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCombinedFragmentAdapter() {
		return new CombinedFragmentItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Continuation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createContinuationAdapter() {
		return new ContinuationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ConsiderIgnoreFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConsiderIgnoreFragmentAdapter() {
		return new ConsiderIgnoreFragmentItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CallEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCallEventAdapter() {
		return new CallEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ChangeEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createChangeEventAdapter() {
		return new ChangeEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.SignalEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSignalEventAdapter() {
		return new SignalEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.AnyReceiveEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAnyReceiveEventAdapter() {
		return new AnyReceiveEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CreateObjectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCreateObjectActionAdapter() {
		return new CreateObjectActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DestroyObjectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDestroyObjectActionAdapter() {
		return new DestroyObjectActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TestIdentityAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTestIdentityActionAdapter() {
		return new TestIdentityActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadSelfAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadSelfActionAdapter() {
		return new ReadSelfActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadStructuralFeatureAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadStructuralFeatureActionAdapter() {
		return new ReadStructuralFeatureActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ClearStructuralFeatureAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClearStructuralFeatureActionAdapter() {
		return new ClearStructuralFeatureActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.RemoveStructuralFeatureValueAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRemoveStructuralFeatureValueActionAdapter() {
		return new RemoveStructuralFeatureValueActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.AddStructuralFeatureValueAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAddStructuralFeatureValueActionAdapter() {
		return new AddStructuralFeatureValueActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LinkEndData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLinkEndDataAdapter() {
		return new LinkEndDataItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.QualifierValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createQualifierValueAdapter() {
		return new QualifierValueItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadLinkAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadLinkActionAdapter() {
		return new ReadLinkActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LinkEndCreationData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLinkEndCreationDataAdapter() {
		return new LinkEndCreationDataItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CreateLinkAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCreateLinkActionAdapter() {
		return new CreateLinkActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DestroyLinkAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDestroyLinkActionAdapter() {
		return new DestroyLinkActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LinkEndDestructionData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLinkEndDestructionDataAdapter() {
		return new LinkEndDestructionDataItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ClearAssociationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClearAssociationActionAdapter() {
		return new ClearAssociationActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.BroadcastSignalAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createBroadcastSignalActionAdapter() {
		return new BroadcastSignalActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.SendObjectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSendObjectActionAdapter() {
		return new SendObjectActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ValueSpecificationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createValueSpecificationActionAdapter() {
		return new ValueSpecificationActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TimeExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTimeExpressionAdapter() {
		return new TimeExpressionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Duration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDurationAdapter() {
		return new DurationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ValuePin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createValuePinAdapter() {
		return new ValuePinItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DurationInterval}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDurationIntervalAdapter() {
		return new DurationIntervalItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Interval}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createIntervalAdapter() {
		return new IntervalItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TimeConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTimeConstraintAdapter() {
		return new TimeConstraintItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.IntervalConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createIntervalConstraintAdapter() {
		return new IntervalConstraintItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TimeInterval}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTimeIntervalAdapter() {
		return new TimeIntervalItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DurationConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDurationConstraintAdapter() {
		return new DurationConstraintItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TimeObservation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTimeObservationAdapter() {
		return new TimeObservationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DurationObservation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDurationObservationAdapter() {
		return new DurationObservationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.OpaqueAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOpaqueActionAdapter() {
		return new OpaqueActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.SendSignalAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSendSignalActionAdapter() {
		return new SendSignalActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CallOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCallOperationActionAdapter() {
		return new CallOperationActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CallBehaviorAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCallBehaviorActionAdapter() {
		return new CallBehaviorActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InformationItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInformationItemAdapter() {
		return new InformationItemItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InformationFlow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInformationFlowAdapter() {
		return new InformationFlowItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Model}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createModelAdapter() {
		return new ModelItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadVariableAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadVariableActionAdapter() {
		return new ReadVariableActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ClearVariableAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClearVariableActionAdapter() {
		return new ClearVariableActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.AddVariableValueAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAddVariableValueActionAdapter() {
		return new AddVariableValueActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.RemoveVariableValueAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRemoveVariableValueActionAdapter() {
		return new RemoveVariableValueActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.RaiseExceptionAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRaiseExceptionActionAdapter() {
		return new RaiseExceptionActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ActionInputPin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActionInputPinAdapter() {
		return new ActionInputPinItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadExtentAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadExtentActionAdapter() {
		return new ReadExtentActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReclassifyObjectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReclassifyObjectActionAdapter() {
		return new ReclassifyObjectActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadIsClassifiedObjectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadIsClassifiedObjectActionAdapter() {
		return new ReadIsClassifiedObjectActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.StartClassifierBehaviorAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createStartClassifierBehaviorActionAdapter() {
		return new StartClassifierBehaviorActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadLinkObjectEndAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadLinkObjectEndActionAdapter() {
		return new ReadLinkObjectEndActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReadLinkObjectEndQualifierAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReadLinkObjectEndQualifierActionAdapter() {
		return new ReadLinkObjectEndQualifierActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CreateLinkObjectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCreateLinkObjectActionAdapter() {
		return new CreateLinkObjectActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.AcceptEventAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAcceptEventActionAdapter() {
		return new AcceptEventActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.AcceptCallAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAcceptCallActionAdapter() {
		return new AcceptCallActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReplyAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReplyActionAdapter() {
		return new ReplyActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.UnmarshallAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnmarshallActionAdapter() {
		return new UnmarshallActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ReduceAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReduceActionAdapter() {
		return new ReduceActionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ControlFlow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createControlFlowAdapter() {
		return new ControlFlowItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.InitialNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInitialNodeAdapter() {
		return new InitialNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ActivityParameterNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivityParameterNodeAdapter() {
		return new ActivityParameterNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ForkNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createForkNodeAdapter() {
		return new ForkNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.FlowFinalNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFlowFinalNodeAdapter() {
		return new FlowFinalNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CentralBufferNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCentralBufferNodeAdapter() {
		return new CentralBufferNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.MergeNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMergeNodeAdapter() {
		return new MergeNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DecisionNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDecisionNodeAdapter() {
		return new DecisionNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ActivityFinalNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActivityFinalNodeAdapter() {
		return new ActivityFinalNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.JoinNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createJoinNodeAdapter() {
		return new JoinNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.DataStoreNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDataStoreNodeAdapter() {
		return new DataStoreNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ObjectFlow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createObjectFlowAdapter() {
		return new ObjectFlowItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.SequenceNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSequenceNodeAdapter() {
		return new SequenceNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ConditionalNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConditionalNodeAdapter() {
		return new ConditionalNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Clause}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClauseAdapter() {
		return new ClauseItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.LoopNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLoopNodeAdapter() {
		return new LoopNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExpansionNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExpansionNodeAdapter() {
		return new ExpansionNodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExpansionRegion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExpansionRegionAdapter() {
		return new ExpansionRegionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ComponentRealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createComponentRealizationAdapter() {
		return new ComponentRealizationItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createComponentAdapter() {
		return new ComponentItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Node}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNodeAdapter() {
		return new NodeItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.Device}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDeviceAdapter() {
		return new DeviceItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ExecutionEnvironment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createExecutionEnvironmentAdapter() {
		return new ExecutionEnvironmentItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.CommunicationPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCommunicationPathAdapter() {
		return new CommunicationPathItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.FinalState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFinalStateAdapter() {
		return new FinalStateItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.TimeEvent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTimeEventAdapter() {
		return new TimeEventItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.ProtocolTransition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProtocolTransitionAdapter() {
		return new ProtocolTransitionItemProvider(this);
	}

	/**
	 * This creates an adapter for a {@link org.eclipse.uml2.uml.AssociationClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAssociationClassAdapter() {
		return new AssociationClassItemProvider(this);
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null
			? this
			: parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(
			ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForTypeGen(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	public boolean isFactoryForType(Object type) {
		return isFactoryForTypeGen(type)
			|| (type instanceof EPackage && UMLUtil.getProfile((EPackage) type) != null)
			|| (type instanceof EObject && UMLUtil
				.getStereotype((EObject) type) != null);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class)
				|| (((Class) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * Associates an adapter with a notifier via the base implementation, then records it to ensure it will be disposed.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void associate(Adapter adapter, Notifier target) {
		super.associate(adapter, target);
		if (adapter != null) {
			disposable.add(adapter);
		}
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		disposable.dispose();
	}

	public Adapter createAdapter(Notifier target) {
		Adapter adapter = super.createAdapter(target);
		return adapter == null
			? stereotypeApplicationItemProvider
			: adapter;
	}

}
